version: '3.1'
services:
  {{.ProjectName}}:
    build:
      context: ../../..
      dockerfile: Dockerfile-builder
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    environment:
      HTTP_PORT: 8080
      PPROF_ENABLED: 'true'
      PPROF_PORT: 9000
      GRPC_PORT: 50051
      PUBSUB_EMULATOR_HOST: "pubsub:8095"
    ports:
      - "8080:8080"
    depends_on:
      - pubsub
    networks:
      - intranet

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - intranet

  redis:
    image: redis:alpine
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    networks:
      - intranet

  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:380.0.0-emulators
    entrypoint: gcloud beta emulators pubsub start --project=project-id --host-port=0.0.0.0:8095
    restart: unless-stopped
    ports:
      - "8095:8095"
    networks:
      - intranet

  consul:
    image: consul
    volumes:
      - .:/app
    ports:
      - "8500:8500"
    networks:
      - intranet

networks:
  intranet:
    driver: bridge